### ISSUE TITLE
Listing view of media - content to display

### ISSUE THREAD

**Issue by ludovicrenevey** [Fonsart/NHdesign#2]
In the exemple of Yann : 
1. icon + title
2. text description
3. number of comments
4. image

In the wireframe of Noémie : 
1. icon + title
2. text description
3. number of comments
4. image
_5. tags_
_6. nom prénom auteur_

**Comment by ianprince** [comment]
URLs pour les deux ?

**Comment by ludovicrenevey** [comment]
Bonjour Ian, 

Tu parles d'avoir accès à ces éléments ou ? Si oui, vous avez tous sur basecamp.

http://fonsart.github.io/NHdesign/templates/demo.html#
https://basecamp.com/3071911/projects/11090190/todos/230119303

**Comment by ianprince** [comment]
Oui, c’est juste pour avoir le bon contexte à tes questions.
