### ISSUE TITLE
Profil page - add a new grafic element

### ISSUE THREAD

**Issue by ludovicrenevey** [Fonsart/NHdesign#36]
We must add a new element on the profil page of the user. 

[vague_profil.eps.zip](https://github.com/Fonsart/NHdesign/files/300383/vague_profil.eps.zip)

Please see this exemple : 

[pages_notrehistoireprofil.pdf](https://github.com/Fonsart/NHdesign/files/300385/pages_notrehistoireprofil.pdf)

**Comment by tonifisler** [comment]
@ludovicrenevey I don't understand what is missing from the current version: http://fonsart.github.io/NHdesign/templates/profile-person.html

**Comment by ludovicrenevey** [comment]
@tonifisler does it work on IE ? The client does not see it.

**Comment by tonifisler** [comment]
It works on all browsers ;)
