### ISSUE TITLE
Home page's first picture - display problem on Firefox PC 2.0.5

### ISSUE THREAD

**Issue by ludovicrenevey** [Fonsart/NHdesign#39]
We have a problem with the first image. The original format is not respected.  @tonifisler 

![image001](https://cloud.githubusercontent.com/assets/12033929/15857748/466c1cc8-2cbd-11e6-8854-cd0a2219f368.png)

**Comment by tonifisler** [comment]
Can't reproduce

![screen shot 2016-06-07 at 16 31 49](https://cloud.githubusercontent.com/assets/1708450/15861709/811dd05e-2ccd-11e6-80f9-5076369d3ccd.png)
