### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by guillaumeberry-zz** [Fonsart/NHdesign#4]
Let's regroup here the adjustment needs/change for the type settings
- [ ] We need to find a better Serif font…
- [ ] Decrease base font size (for Work Sans - suggested by Ian), let's try with 16px

**Comment by guillaumeberry-zz** [comment]
I've made some HTML tweaks to use Work Sans for articles tiles…
![test-tuiles-articles](https://cloud.githubusercontent.com/assets/1800253/12802727/e4930a82-cab2-11e5-92ea-b9a32444352e.png)
- Do we want to have different sizes based on text length to create a organic feeling
- Smaller sizes (as requested by Ian)
- Do we need a light weight for Work Sans…

**Comment by guillaumeberry-zz** [comment]
Let's test **Source Serif** font!
https://www.google.com/fonts#UsePlace:use/Collection:Source+Serif+Pro:400,700

**Comment by ludovicrenevey** [comment]
@guillaumeberry : have you seen this comment on Invision ?

=> Patrick + Ian do not like serif for text. Maybe we should not take it into account but important to notice :) 

![screen shot 2016-02-04 at 09 45 18](https://cloud.githubusercontent.com/assets/12033929/12810074/055542dc-cb24-11e5-8f5a-24e057dcd058.png)

**Comment by ianprince** [comment]
Merci pour les retours, Je regarde les propositions et reviens rapidement vers vous,

**Comment by ludovicrenevey** [comment]
@ianprince : juste une information importante. Ces éléments sont en review interne et dès que nous serons satisfait, nous les montrerons à l'équipe. Aucun problème cependant à ce que tu mettes déjà tes commentaires :)

**Comment by ianprince** [comment]
@ludovicrenevey 
OK, dans ce cas je préfère attendre, merci de me dire quand c'est finalisé

**Comment by guillaumeberry-zz** [comment]
@Yago I'm making some mockups tests for Source Serif Pro from here : https://github.com/adobe-fonts/source-serif-pro
