### ISSUE TITLE
Filters column

### ISSUE THREAD

**Issue by guillaumeberry-zz** [Fonsart/NHdesign#6]
- [x] Remove background color (so the media grid is more visible
- [ ] First filter group open by default, the other ones closed (ask Noémie & Marc first :p)

And a little mockup!
![filters](https://cloud.githubusercontent.com/assets/1800253/12802213/2edc8abc-cab0-11e5-9d5a-1625565b7c12.png)

**Comment by Yago** [comment]
reviewable in http://fonsart.github.io/NHdesign/molecules.html#facet-group
