### ISSUE TITLE
Review 

### ISSUE THREAD

**Issue by zufrieden** [Fonsart/NHdesign#9]
- [x] Add alerts (success, info, ...) element (bootstrap style) and place it in the main interface under topbar but not fixed
- [x] "Load more" button under media grid/list
- [x] loading gif
- [x] search toolbar ("trier par select"use select for filter, don't overdesign) [Printscreen](https://cloud.githubusercontent.com/assets/451236/13461295/dae6d67e-e080-11e5-9fdc-4b1ffda340b9.png)
- [x] Add tags with (x) under "29 résultats pour "chat"" with selected facets.
- [x] update line-height on grid objects
- [x] open/close all facets, right align and small button [print screen](https://cloud.githubusercontent.com/assets/451236/13461305/e196f81e-e080-11e5-840f-9a01af249df4.png)

**Comment by Yago** [comment]
Alert components done in release [`0.4.1`](https://github.com/Fonsart/NHdesign/releases/tag/0.4.1)

**Comment by Yago** [comment]
Continue on PR #12
